version: '3'

services:
    php-fpm:
        build:
            context: .
            dockerfile: ./docker/php-fpm/Dockerfile
        container_name: "laravel-store-app"
        restart: unless-stopped
        depends_on:
            - db
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./docker/php-fpm/local.ini:/usr/local/etc/php/conf.d/local.ini
            - ./docker/php-fpm/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
        networks:
            - app-network

    db:
        image: mysql:5.7
        container_name: "laravel-store-db"
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - dbdata:/var/lib/mysql/
            - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
            - ./docker/var/log/mysql:/var/log/mysql
        networks:
            - app-network

    webserver:
        image: nginx
        container_name: "laravel-store-nginx"
        restart: unless-stopped
        ports:
            - "8098:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/local.conf:/etc/nginx/conf.d/default.conf
            - ./docker/var/log/nginx:/var/log/nginx
        depends_on:
            - php-fpm
        networks:
            - app-network


networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local